name: build-aseprite-latest
on:
  workflow_dispatch:
jobs:
  start-build:
    name: "开始编译最新版aseprite"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: download_latest_version
        shell: bash
        run: |
          SKIAVERSION="$(curl https://api.github.com/repos/aseprite/skia/releases/latest | jq -r .tag_name)"
          VERSION="$(curl https://api.github.com/repos/aseprite/aseprite/releases/latest | jq -r .tag_name)"
          mkdir -p Aseprite build skia
          curl -LO "https://github.com/aseprite/aseprite/releases/download/$VERSION/Aseprite-$VERSION-Source.zip"
          unzip -qo Aseprite-$VERSION-Source.zip -d Aseprite
          curl -LO "https://github.com/aseprite/skia/releases/download/$SKIAVERSION/Skia-Windows-Release-x64.zip"
          unzip -qo Skia-Windows-Release-x64.zip -d skia
          ls
          cd build
          for i in c++ cpp gcc g++ cc ar as ld nm ranlib windres gfortran make mingw32-make ccache
          do
            while rm -v $(which $i)
            do
              :
            done
          done
          cat <<'EOF' > build.bat
            echo build.bat_start
            for /f "usebackq delims=" %%i in (`vswhere.exe -latest -property installationPath`) do call "%%i\VC\Auxiliary\Build\vcvars64.bat"
            cmake -DSKIA_DIR=..\skia -DSKIA_LIBRARY_DIR=..\skia\out\Release-x64 -DSKIA_LIBRARY=..\skia\out\Release-x64\skia.lib -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -G Ninja ..\Aseprite
            ninja aseprite
            echo build.bat_end
          EOF
      - name: build
        shell: cmd
        run: |
          dir
          cd build
          build.bat
      - name: upload-build-file
        uses: actions/upload-artifact@v3
        with:
          name: build_Aseprite
          path: build/bin/